### ISSUE TITLE
[FEATURE] Put a 'Home button' in navigation

### ISSUE THREAD

**Issue by Shantanu-Meta** [arpitghura/typing-test#101]
Hey @arpitghura 
I think as there is only one button named as "Typing Test" to go to the landing page/home page. It may be problem to user to go to home page.
Can I make add a home button in navigation bar to put more clarification ?
It will look like: 
![image](https://user-images.githubusercontent.com/117648930/216681324-7b95fba6-f533-40bf-8224-4ee50e029954.png)

**Comment by arpitghura** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face: <br/> You should join our <a href='https://discord.gg/7c3VGDutmS'>Discord</a> chat - we help and encourage each other to contribute to open source little and often

**Comment by Tapo41** [comment]
I want to contribute to this.. 
Please assign it to me

**Comment by Shantanu-Meta** [comment]
@arpitghura as this is is pulled by me, I hope this should be assigned to me if it looks relevant to you.

**Comment by arpitghura** [comment]
We had the button previously, but we have removed as in modern website there is no separate button to go home page. This can be carried out with the logo or through the title of the website.
