### ISSUE TITLE
improving ui [FEATURE]

### ISSUE THREAD

**Issue by leesha19** [arpitghura/typing-test#102]
**Is your feature request related to a problem? Please describe.**
the ui of the website should be very intresting and interacting 

**Describe the solution you'd like**
i want to make the ui very beautiful
**Describe alternatives you've considered**

**Comment by arpitghura** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face: <br/> You should join our <a href='https://discord.gg/7c3VGDutmS'>Discord</a> chat - we help and encourage each other to contribute to open source little and often

**Comment by arpitghura** [comment]
Hey, can you please tell me why this issue is created and what do you want to do with the UI?

**Comment by Savio629** [comment]
Are you going to work on this @leesha19 ?
Also have you decided on any theme?

**Comment by leesha19** [comment]
> Hey, can you please tell me why this issue is created and what do you want to do with the UI?

the colors used in the website are so childish like having so many colors disturbs the eyes we can just change the color pallete

**Comment by arpitghura** [comment]
> > Hey, can you please tell me why this issue is created and what do you want to do with the UI?
> 
> the colors used in the website are so childish like having so many colors disturbs the eyes we can just change the color pallete

So which color scheme you would like to integrate in the project that will look impressive.

**Comment by arpitghura** [comment]
If you want to contribute check out #81
