### ISSUE TITLE
Add Badges in README file 

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/typing-test#103]
**Is your feature request related to a problem? Please describe.**
Currently the README file do not have badges for the events the project is participating in including DIVERSION 2023 and IWOC 2023.
Also the year of KWOC participation of the project is written wrong (it's 2022) at the end of the README file. 

**Describe the solution you'd like**
- [x] Badges similar to this for both events listed above. 
![badge example](https://user-images.githubusercontent.com/41796013/216790350-bbe56d1b-2aa6-4ad0-829d-7dbce5444d4a.png)

- [x] Update the Year of the participation in KWOC. 
- [x] Add a Badge to join the Discord server ( Link: [https://discord.gg/7c3VGDutmS](https://discord.gg/7c3VGDutmS) ) 

**Describe alternatives you've considered**
You can use [https://shields.io/](https://shields.io/) for creating badges.

**Comment by niladrix719** [comment]
can i work on this?

**Comment by alokvns48** [comment]
Enable the widget setting on the server
Rest above tasks is completed

**Comment by Shantanu-Meta** [comment]
okay i can notice that the year of KWOC is still 2022 and discord badge is not attached. So i can do that please assign me.

**Comment by Shantanu-Meta** [comment]
I have made the enhancement , kindly verify the pr.
