### ISSUE TITLE
[ENHANCEMENT] Refactor the Code

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/typing-test#104]
The Code of the project is not yet refactored. I have seen the same code is available on different files. 
I want that the code should be refactored so that there will be no repetition of the same code.

Current Folder Structure:
![image](https://user-images.githubusercontent.com/41796013/216791074-1daa1326-4c27-43b2-9664-a476599a9339.png)
![image](https://user-images.githubusercontent.com/41796013/216791087-d467e720-9f51-4805-9001-7e37ef961c84.png)

CSS files needs to be refactored first and then JavaScript files without breaking the working of the website.

**Comment by niladrix719** [comment]
can i work on this?

**Comment by rt-001** [comment]
i will like to work on this.

**Comment by Bharadwajshivam28** [comment]
@arpitghura Assign this to me sir

**Comment by arpitghura** [comment]
Let's assign this on First Come basis. So @niladrix719 you can start working on it. I am assigning this issue to you.

**Comment by arpitghura** [comment]
Hey @niladrix719 are you working on this issue?

**Comment by Bharadwajshivam28** [comment]
@arpitghura sir give me chance

**Comment by Bharadwajshivam28** [comment]
I will make it done by tommorow

**Comment by ananyakushal** [comment]
Hey @arpitghura please assign me this task under IWOC'23.

**Comment by arpitghura** [comment]
Go ahead @ananyakushal

**Comment by ananyakushal** [comment]
Hey @arpitghura I have submitted the given task. Please have a look on it.

**Comment by ananyakushal** [comment]
Is there any issue with the code? If not, kindly merge it.

**Comment by arpitghura** [comment]
Actually, I am reviewing it so it might take some time. But don't worry I will merge it soon after reviewing.

**Comment by ananyakushal** [comment]
Ok, please try to review it today only as today is the last day to contribute under IWOC'23. 😊
