### ISSUE TITLE
[FEATURE] Profile data UI enhncement.

### ISSUE THREAD

**Issue by Shantanu-Meta** [arpitghura/typing-test#117]
In profile section the data presentation table is not matching with website theme and other border related enhancement should be there.

**Comment by arpitghura** [comment]
Go ahead @Shantanu-Meta

**Comment by Shantanu-Meta** [comment]
I have made the pr, kindly check and advise if any requirement is necessary.

**Comment by arpitghura** [comment]
Are you contributing through any event?

**Comment by Shantanu-Meta** [comment]
yes i am contributing through DIVERSION 2023.
