### ISSUE TITLE
Add CONTRIBUTING.md 

### ISSUE THREAD

**Issue by A91y** [arpitghura/typing-test#120]
For best practice, CONTRIBUTING.md can be added into this project.

**Comment by A91y** [comment]
Please assign me this issue.

**Comment by arpitghura** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face: <br/> You should join our <a href='https://discord.gg/7c3VGDutmS'>Discord</a> chat - we help and encourage each other to contribute to open source little and often

**Comment by arpitghura** [comment]
@A91y Go ahead
