### ISSUE TITLE
 Writing Documentation of Project in HIndi Language

### ISSUE THREAD

**Issue by Bharadwajshivam28** [arpitghura/typing-test#123]
Hello Respected Sir
   If you like my idea then we can write a Documentation on this project in Hindi Language

Aim of writing Document of Project in  Hindi Language is that Many people understand Hindi language well so one can read the documentation in Hindi language and understand Project well

If you like my idea than we can move ahead

**Comment by arpitghura** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face: <br/> You should join our <a href='https://discord.gg/7c3VGDutmS'>Discord</a> chat - we help and encourage each other to contribute to open source little and often

**Comment by Bharadwajshivam28** [comment]
ok sir @arpitghura
