### ISSUE TITLE
[FEATURE] add a brand logo for typing-test

### ISSUE THREAD

**Issue by chikkibum** [arpitghura/typing-test#124]
I will be adding svg icon for typing test brand to make it look more pleasing

**Comment by arpitghura** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face: <br/> You should join our <a href='https://discord.gg/7c3VGDutmS'>Discord</a> chat - we help and encourage each other to contribute to open source little and often

**Comment by arpitghura** [comment]
Go ahead and make the svg. I wanted to know how you are going to make it?

**Comment by riyasinghsirohi** [comment]
I would like to contibute over this issue

**Comment by chikkibum** [comment]
hi @riyasinghsirohi i am currently working on this issue.

**Comment by arpitghura** [comment]
Hey, @chikkibum are you working on this issue?

**Comment by chikkibum** [comment]
@arpitghura hate to bring this news but i won't be able to work on this issue due to lack of time for this
