### ISSUE TITLE
Upgrade README file

### ISSUE THREAD

**Issue by Suryansh1720001** [arpitghura/typing-test#129]
Hello @arpitghura 

*Is your feature request related to a problem? Please describe.*
### Features that I want to add in README File

- Project admin details
- Add the contributing line with a guideline link so that everyone motivates by that.
- Center heading for more attractive
- adding the footer part in readme file

*Describe the solution you'd like*

- Add new features

Kindly assign this issue to me under IWOC event with the label of medium.

**Comment by arpitghura** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face: <br/> You should join our <a href='https://discord.gg/7c3VGDutmS'>Discord</a> chat - we help and encourage each other to contribute to open source little and often

**Comment by Suryansh1720001** [comment]
Kindly assign this to me
