### ISSUE TITLE
Improve Nav Bar UI & Footer Location

### ISSUE THREAD

**Issue by iharshka** [arpitghura/typing-test#13]
@arpitghura I have worked on the UI of the navbar to make it look more attractive and appealing. 
Here is how it looked:
![Screenshot (2063)](https://user-images.githubusercontent.com/106887668/195328720-46e3f661-1b11-41f9-acb8-e6462c67fce3.png)

When we will hover on the nav buttons they will turn to black with white text on it.
Moreover, we can work on the footer to move it to the bottom center.

**Comment by arpitghura** [comment]
@iharshka can you share a video that justifies what you are talking about navbar?

Also, Sibayan is already working on the footer part.

**Comment by iharshka** [comment]
https://user-images.githubusercontent.com/106887668/195656389-78227220-64b7-4974-98fe-8e1822558018.mp4

**Comment by arpitghura** [comment]
Hey @iharshka Thanks for your suggestion but I think this doesn't create a good impact on end user. So that's why I am closing this issue.
