### ISSUE TITLE
[BUG] Obstructed lines in 5 minutes challenge

### ISSUE THREAD

**Issue by Pritam1136** [arpitghura/typing-test#132]
**Obstructed lines below the header or some other element in 5 minutes challenge. This problem occurs not only in smartphones but also in computer.**

**Steps to reproduce the behavior:**
1. Go to the typing test application. 
2. Click on practice ang select the 5 minutes challenge.
3. Begin typing the provided text.

**Expected behavior**
The lines of text in the 5 minutes challenge should be displayed clearly and without any obstruction, allowing the user to read and type the text smoothly.

**Screenshot**
![Screenshot 2023-05-28 080659](https://github.com/arpitghura/typing-test/assets/126561455/12d8550e-9c71-4b4c-b514-383e78e09c2f)

**Environment:**
 -  OS- Windows 10
 -  Browser- chrome, edge
 -  Device- Desktop, Laptop

**Additional context**
-  This issue occurs consistently during the 5-min challenge.
-  I have tested it on multiple browsers (e.g., Chrome , Firefox) with the same result.
-  Adjusting the screen size does not resolve the issue.

**Comment by arpitghura** [comment]
Yeah, I have seen this issue in 5 mins challenge. I will try to fix this issue. If you have any ideas or want to work on this issue, please share 😊

**Comment by Pritam1136** [comment]
Hello @arpitghura 

 I would love to work on it, please assign it to me.

**Comment by arpitghura** [comment]
Go for it ✨

**Comment by arpitghura** [comment]
Unassigning
