### ISSUE TITLE
Placing textbox on screen

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/typing-test#134]
The issue comes in easy and intermediate sessions in which the length of the sentence is less. so, in this case, the textbox should be available right below the reset button. and in the case of long sessions in intermediate and hard difficulty levels where text size is sufficiently large then the behavior of putting the textbox out of the original position and lies in the center-bottom area.

![image](https://github.com/arpitghura/typing-test/assets/41796013/22049d50-fa03-4bfa-9133-accfcce4f4f3)

_Originally posted by @arpitghura in https://github.com/arpitghura/typing-test/issues/133#issuecomment-1582794780_

**Comment by arpitghura** [comment]
Hey @sarthakvermaa I have updated the issue, and now it looks very much to the point. you can look at it.

**Comment by arpitghura** [comment]
Sarthak, you have to make the text box inline that is placed just below the reset button when the `dynamic-text-box` height is less than 80% of the viewport height and when the height is greater than 80% then the current behaviour is already written. 

The height is less in case of easy and intermediate difficulty and in case of less time sessions and also do check about these.

**Comment by Swap-nil-2003** [comment]
Hey @arpitghura is this issue still active? If not resolved yet, could I be assigned to it?
