### ISSUE TITLE
Add Github Project Link on website

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/typing-test#14]
Add the GitHub Project link in the Navbar or the footer of the website so that visitors may view the GitHub repo and they can contribute to the project if they wanted to.

**Comment by SubhamChoudhury** [comment]
Hi @arpitghura, can you assign this to me?

**Comment by Miteshhsingla** [comment]
hey i want to work on this issue

**Comment by RohitSaklani** [comment]
hey can you assign it to me

**Comment by iharshka** [comment]
Hey @arpitghura,
Hope you're doing great!
I am interested in working on the code part too of this repo. I can work on this issue faster.
Kindly assign it to me.

**Comment by SubhamChoudhury** [comment]
Hey @arpitghura, is it okay to replace either `Typing Test` or `Practice` in the navbar with the GitHub Icon and Link, since both redirect to the same page?

**Comment by arpitghura** [comment]
> Hey @arpitghura, is it okay to replace either `Typing Test` or `Practice` in the navbar with the GitHub Icon and Link, since both redirect to the same page?

Okay Replace `typing test` and add GitHub icon with link at the end of all links.
