### ISSUE TITLE
Add Difficulty levels

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/typing-test#2]
**Is your feature request related to a problem? Please describe.**
Currently there is no option to set difficulty level. So, add an option to set the difficulty level for practice and test and based upon difficulty level, create sentence to type. 

**Describe the solution you'd like**
Add a page similar to `practice.html` which also asks user to set difficulty level before proceeding and based on difficulty level, make sentence to type in.

**Comment by arpitghura** [comment]
Hey, @maciek04786 Welcome to the community.
Could you please share your approach on how you are going to implement this?

**Comment by maciek04786** [comment]
> Hey, @maciek04786 Welcome to the community.
> Could you please share your approach on how you are going to implement this?

I was thinking about using a dictionary with three level, first level being only lowercase letter, second level could be what it is now (lowercase and uppercase letters) and third level with lowercase, uppercase as well as numbers. I could add some radio buttons to let the user choose the level. What do you think about this approach?

**Comment by arpitghura** [comment]
@maciek04786 go on.

> > Hey, @maciek04786 Welcome to the community.
> > Could you please share your approach on how you are going to implement this?
> 
> I was thinking about using a dictionary with three level, first level being only lowercase letter, second level could be what it is now (lowercase and uppercase letters) and third level with lowercase, uppercase as well as numbers. I could add some radio buttons to let the user choose the level. What do you think about this approach?

**Comment by arpitghura** [comment]
Thank you @maciek04786 for your contribution.
