### ISSUE TITLE
Build About Page

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/typing-test#22]
**Is your feature request related to a problem? Please describe.**
The website contains a link to the `about project` page but the page is empty.

**Describe the solution you'd like**
Edit the `about.html` file and add content along with graphics to look like a about us/project page.

- [ ] add Navbar similar to homepage
- [ ] add hero section similar to homepage but add content related to about page- 
- [ ] add details about the project.
- [ ] add footer similar to homepage

**Comment by tanyaa-arora** [comment]
Hi @arpitghura I'd like to work on this issue

**Comment by arpitghura** [comment]
Hey @tanyaa-arora welcome to the community 
since @emday4prez has already opened the PR for this issue, you can look into some other issues.
