### ISSUE TITLE
Build Profile Page

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/typing-test#25]
**Is your feature request related to a problem? Please describe.**
The website contains a link to the `profile` page but the page is empty.

**Describe the solution you'd like**
Edit the `profile.html` file and add content along with graphics to look like a profile page.

- [ ] add Navbar similar to homepage
- [ ] add hero section similar to homepage 
- [ ] show user data from local Storage like username, history of practice session.
- [ ] add button to delete all the data from the local Storage.
- [ ] add footer similar to homepage

**Comment by mdhinesh** [comment]
Hey, please assign this issue to me?

**Comment by arpitghura** [comment]
Hey @mdhinesh go for this.
