### ISSUE TITLE
Improper showing of table on smartphones

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/typing-test#26]
**Describe the bug**
The history table on practice page is not showing responsively on small screen devices. 

**To Reproduce**
1. Go to `practice.html`
2. Fill details and complete one practice session
3. Scroll down to `history`
4. You will see a table which is not responsive.

**Expected behavior**
Make the history table responsive by adding a horizontal scrollbar for small screen devices. This can easily be done using `overflow` property.

**Screenshots**
![Screenshot_2022-10-16-15-38-18-32_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/41796013/196029683-948b0027-cf5a-4cc9-8ad1-8a6cf5f209c1.jpg)

![Screenshot_2022-10-16-15-38-27-20_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/41796013/196029714-588c88c3-ae8d-4a53-8d85-ab990455adaa.jpg)

**Smartphone (please complete the following information):**
 - Device: Realme X7 
 - OS: Android 12
 - Browser: Chrome

**Comment by Yushmanth-reddy** [comment]
hey @arpitghura can you assign me this issue

**Comment by arpitghura** [comment]
Hey, @Yushmanth-reddy Welcome to the community.
You can start working on this issue.
