### ISSUE TITLE
Add Navbar and Footer on practice page

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/typing-test#32]
There is no navigation menu and footer available on the `practice.html` page. 

Add the navigation menu and footer similar to `index.html`

**Comment by dissyulina** [comment]
Hi, I would like to work on this. Please assign this to me.

**Comment by arpitghura** [comment]
Hey, @dissyulina Welcome to the Community. You can start working on it.

**Comment by siddhesh-coder** [comment]
assign me

**Comment by dissyulina** [comment]
Hi @arpitghura, sorry I've just got back from my work. I am working on this issue right now, please wait for me :).
Do you want to also make the overall styling on the practice page the same with the homepage (i.e. blue background surrounding the content with white background with some border radius)? Or strictly just Navbar and Footer?

**Comment by arpitghura** [comment]
We want only the navBar and footer,
No blue background or border radius on the content section.

> Hi @arpitghura, sorry I've just got back from my work. I am working on this issue right now, please wait for me :). Do you want to also make the overall styling on the practice page the same with the homepage (i.e. blue background surrounding the content with white background with some border radius)? Or strictly just Navbar and Footer?

**Comment by dissyulina** [comment]
Got it! But the Navbar and Footer should still have the same styling as homepage (blue background with white font), right?

**Comment by dissyulina** [comment]
Hey @arpitghura , if you want something changed please let know.

**Comment by arpitghura** [comment]
The Issue is now solved, so I am closing it. 
and one point to remember _Always raise PR for any issue if you are assigned for that._
