### ISSUE TITLE
Add Time Based Practice Sessions

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/typing-test#35]
**Is your feature request related to a problem? Please describe.**
Currently we have only level-based practice session but there is no way to give long practice session like `1 minute`, `5 minutes`, etc.

**Describe the solution you'd like**
We can implement the timing-based sessions in `practice.html` while choosing the difficulty level like we can give options `auto` or `select time span` 

**Additional context**
In implementing the timing-based session, we need to generate a long paragraph so that the words will not lack.

**Comment by BoshraJaber** [comment]
I can do it @arpitghura

**Comment by arpitghura** [comment]
Hey, @BoshraJaber You can start working on it.

**Comment by arpitghura** [comment]
I have added this enhancement to the App. So, closing this issue.
