### ISSUE TITLE
Add Side Menu

### ISSUE THREAD

**Issue by mdhinesh** [arpitghura/typing-test#36]
**Describe the bug**
When the application in mobile view the navbar collapses.

**Expected behavior**
When the application's width is less than 450px(which is the most of mobile phone's width) an hamburger icon appears and a side menu is created.

![image](https://user-images.githubusercontent.com/58901210/198234659-e84b1e2e-96c1-42d4-adb6-a69e7af8fe6e.png)

**Comment by Jideotetic** [comment]
I will like to work on this, kindly assign it to me

**Comment by arpitghura** [comment]
Hey, @Jideotetic Welcome to the community. I am assigning you for this issue. You can now start your work.

**Comment by divyang9575** [comment]
@arpitghura please assign this issue to me

**Comment by arpitghura** [comment]
Closing this issue as the work is completed.
