### ISSUE TITLE
Add Difficulty level in history 

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/typing-test#39]
Add Difficulty level in history, also store it with individual practice session in local Storage.

**Comment by arpitghura** [comment]
Hey, @imThiyagu You can start working on the issue. Greatly explained.

**Comment by imThiyagu** [comment]
Thanks for the assignment :) 

Could you pls review the changes #40 

<hr>
<img width="1440" alt="Screenshot 2022-10-29 at 10 35 06 PM" src="https://user-images.githubusercontent.com/27724580/198844785-1a4f1e64-375c-420a-a414-8790f9c82a19.png">


Are we good with the changes?

**Comment by arpitghura** [comment]
Yeah, Great work.
