### ISSUE TITLE
Want to add a "FAVICON".

### ISSUE THREAD

**Issue by divyang9575** [arpitghura/typing-test#41]
please assign me this issue and add hacktoberfest tag.

**Comment by arpitghura** [comment]
Hey, @divyang9575 you can start your work.

**Comment by arpitghura** [comment]
Hey @divyang9575 are you working on the issue?

**Comment by arpitghura** [comment]
Due to no response on previous message, I am removing you @divyang9575 from this assignment. 
Thank you for your contributions.

**Comment by arpitghura** [comment]
Now, the website has favicon icon, so I am closing this issue.
