### ISSUE TITLE
Add animation to heading

### ISSUE THREAD

**Issue by CoderAayush2104** [arpitghura/typing-test#43]
Please assign this to me . I will do it for you.

**Comment by arpitghura** [comment]
Can you please elaborate what you wanted to do?
What end result will look like?

**Comment by arpitghura** [comment]
I don't want to add any. If you would like to add any, please do share

**Comment by chiragtyagi2003** [comment]
A simple hover-over zoom-in transition effect will give a nice effect. I would like to contribute.

**Comment by arpitghura** [comment]
I don't think this will create any impact.
So I am closing this issue as this will not create any confusion for other contributors. 

You can think some other ideas or find some bug on website or solve existing issue.
