### ISSUE TITLE
Add average time and speed to history section

### ISSUE THREAD

**Issue by alexsam29** [arpitghura/typing-test#44]
I'd like to add a section in the history table that shows the average typing speed and average time of all speed tests taken by the user.

 Something like this:
<img width="877" alt="image" src="https://user-images.githubusercontent.com/69481177/198865310-68b08368-439a-40e8-a8aa-61c477e42fa4.png">

I haven't seen any existing issues for this.  I'd like to be assigned this, let me know if this is something I can add for Hacktoberfest.

**Comment by arpitghura** [comment]
Yeah, this is great idea @alexsam29 you can start working on it.
