### ISSUE TITLE
Remove Extra Spacing of Name Div

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/typing-test#45]
**Describe the bug**
The `NameModal` div on `practice` page has unwanted vertical spacing that looks unprofessional.

**To Reproduce**
1. Go to `practice.html`
2. Click on `Reset Data` if already name and history is saved.
3. Scroll to `name asking div`
4. See extra spacing of name div in vertical direction

**Expected behavior**
The name div should have the height which contains the content not extra space.

**Screenshots**
![image](https://user-images.githubusercontent.com/41796013/198866692-c86d6571-5078-4dc9-9e9b-456a89ee8921.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge

**Expected Solution**
This problem can easily be solved by removing the `height` property from the `nameModal` div.

**Comment by priyanshu2k3** [comment]
assign this to me

**Comment by arpitghura** [comment]
Hey, @priyanshu2k3 you can start working on the issue.

**Comment by priyanshu2k3** [comment]
![1234](https://user-images.githubusercontent.com/100031428/198867578-2ab67dfb-0362-45ec-a067-1cca481be87f.PNG)

like this??

**Comment by arpitghura** [comment]
Yes, you have done in a right way.
