### ISSUE TITLE
Adding light and Dark mode

### ISSUE THREAD

**Issue by priyadarshni-jha** [arpitghura/typing-test#5]
**Is your feature request related to a problem? Please describe.**
No it is not a problem. Add this feature to make the website more appealing.

**Describe the solution you'd like*
Enhancing the website with a light and  dark mode option by adding toggle button

**Comment by arpitghura** [comment]
Thanks, @priyadarshni-jha for sharing such a great idea. Would you like to work on the issue.

**Comment by priyadarshni-jha** [comment]
> Thanks, @priyadarshni-jha for sharing such a great idea. Would you like to work on the issue.

Yeh sure I will be working on this issue.

**Comment by arpitghura** [comment]
@surreal30 you can make use of navBar for the toggle button.

**Comment by arpitghura** [comment]
> Hi, I don't have much experience in front end coding but I would like to contribute in this. Should there be a toggle button for light and dark mode and where should I place it?

If you don't have much experience in front End Development, there is no problem, you can still contribute to the project. Check some non code issue and beginner friendly issue in which you can contribute.

**Comment by arpitghura** [comment]
Hey @priyadarshni-jha and @surreal30 are you guys working on the issue? 

If yes, how much you have done?

**Comment by priyadarshni-jha** [comment]
@arpitghura yes I am working on it

**Comment by pronajitdey** [comment]
I would like to contribute to this issue. Please assign me.

**Comment by arpitghura** [comment]
> @arpitghura yes I am working on it

What is the status of your work?

**Comment by arpitghura** [comment]
Hey @priyadarshni-jha are you currently working on this issue?

**Comment by arpitghura** [comment]
Due to no response of last message, I am removing you @priyadarshni-jha from this assignment.
Thank you for your contributions.

**Comment by arpitghura** [comment]
Good work @ajayanuragi, if you are currently working on this issue. I will assign this to you.

**Comment by ajayanuragi** [comment]
Hey @arpitghura I have created dark  mode for about, profile and practice page. 

Just wanted to know where should i add that button for activating dark mode?

**Comment by arpitghura** [comment]
You can add the button in the navigation menu beside the GitHub icon.

> Hey @arpitghura I have created dark mode for about, profile and practice page.
> 
> Just wanted to know where should i add that button for activating dark mode?

**Comment by somya-kr** [comment]
Hey @arpitghura, Can you assign this issue to me

**Comment by arpitghura** [comment]
Hey @somya-kr Sorry for the late reply. 
Would you like to work on the remaining part of this issue?

**Comment by somya-kr** [comment]
yeah sure.

**Comment by arpitghura** [comment]
The tasks are
1. Add Dark Mode functionality on Index.html
2. Use darkmode icon instead of text. 
3. Fixed the spacing between github icon and darkmode button in navbar on larger screen size display.

**Comment by arpitghura** [comment]
Hey @somya-kr are you still working on the issue? Do you need any help, I will be happy to help you.
