### ISSUE TITLE
Using meaningfull sentences instead of random words.

### ISSUE THREAD

**Issue by Ayush4web** [arpitghura/typing-test#59]
**Let's use some API to get meaningfull sentences**

**Comment by arpitghura** [comment]
Can you suggest some APIs to do that. 

> **Let's use some API to get meaningfull sentences**

**Comment by Ayush4web** [comment]
I have created a pull request in which i am generating random sentence using verbs, adjectives and nouns, with different level of difficulty.

**Comment by Ayush4web** [comment]
Also i am working to create my own API for generating random sentences, will create an issue once completed.

**Comment by arpitghura** [comment]
this issue is fixed by #60 so I am closing this issue. Thank you @Ayush4web for your contributions. Looking for some good contributions.
