### ISSUE TITLE
Add Contributors.md

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/typing-test#6]
Add Contributors.md to thank all the contributors for their support.

**Comment by Giriraj-Roy** [comment]
Hello Sir,

I have gone through the repository and the given instructions. The issue seems to attract my interest and excites me to work on it. I humbly wait for you to assign the task to me if your analysis of my profile allows.

Yours Sincerely,
Giriraj Roy.

**Comment by arpitghura** [comment]
@Giriraj-Roy you can start working on it.

**Comment by arpitghura** [comment]
Hey @Giriraj-Roy you have created the `contributors.md` file by writting manually as far as I understand from the code.

If yes then kindly see some other way to automate the content of file to be updated on every unique PR merged as this will create an issue in updating the file on every new PR merge.

**Comment by Giriraj-Roy** [comment]
Okay, I have figured out that a GitHub Actions Library can be used.
I will be working on it and notify once done.

**Comment by arpitghura** [comment]
All the best @Giriraj-Roy

**Comment by arpitghura** [comment]
Hey @Giriraj-Roy are you working on it?

> Okay, I have figured out that a GitHub Actions Library can be used. I will be working on it and notify once done.

**Comment by arpitghura** [comment]
Hey @Giriraj-Roy I have found the solution and also implemented it. Thank you for your contribution.
