### ISSUE TITLE
Add testimonials section

### ISSUE THREAD

**Issue by Riya14-dangra** [arpitghura/typing-test#63]
As various user test their typing skill on this web application so some of them which have a fastest tying skill and are famous one we have add them as a testimonial

**Comment by Riya14-dangra** [comment]
> As various user test their typing skill on this web application so some of them which have a fastest tying skill and are famous one we have add them as a testimonial

@arpitghura can you please assin this issue to me I want to work on it under kowc2022
Thank you:)

**Comment by arpitghura** [comment]
Hello @Riya14-dangra, Welcome to the community. You can work on this issue. But for getting testimonials, the website must have a form which gets all the testimonials or if you have any other idea. Discuss freely. I am assigning this issue to you. If you have not joined our discord, [Join Discord Server](https://discord.gg/dYdPpAmU)

**Comment by Riya14-dangra** [comment]
> Hello @Riya14-dangra, Welcome to the community. You can work on this issue. But for getting testimonials, the website must have a form which gets all the testimonials or if you have any other idea. Discuss freely. I am assigning this issue to you. If you have not joined our discord, [Join Discord Server](https://discord.gg/dYdPpAmU)

yes sir I think I will add testimonials and text to it I will add contact section in contact section along with the contact details I am going to include the short form where user can have a section of blog and the send submit button so that we recieve the blog and post it as testimonials .....if you like this then I will go for it.

**Comment by arpitghura** [comment]
> 

Yeah, this will be a good option to go for but how do we get those blog/testimonials? 
We can get them either by mail or we have to create a database for them. Do you think of any other options?

**Comment by Riya14-dangra** [comment]
> > 
> 
> Yeah, this will be a good option to go for but how do we get those blog/testimonials? We can get them either by mail or we have to create a database for them. Do you think of any other options?

I think by mail is the easiest and best option

**Comment by arpitghura** [comment]
ok do that and ask me when you need to email address

**Comment by Riya14-dangra** [comment]
> ok do that and ask me when you need the email address

yes sure 
Thank you so much!!

**Comment by arpitghura** [comment]
This issue is fixed by #65 so I am closing this issue.
