### ISSUE TITLE
[BUG] Improper Alignment of Footer Content on Profile and Practice Page on Smartphones

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/typing-test#69]
**Describe the bug**
Improper Alignment of Footer Content on Profile and Practice Page on Smartphones.

**To Reproduce**
1. Go to practice.html
2. Scroll down to footer section
3. See error

**Expected behavior**
The Footer content should be center aligned with relatively small font size similar to footer on index.html

**Screenshots**
![image](https://user-images.githubusercontent.com/41796013/207139927-35e3da98-e44c-4261-9741-2b7e4a369c80.png)

**Expected Solution**
This bug can be solved by checking the CSS of footer content for the media queries of smartphones.

**Comment by Nupoor10** [comment]
Hey can I work on this issue for Kwoc

**Comment by arpitghura** [comment]
Hey, @Nupoor10 Welcome to the community. Yes, you can work on this issue under KWoC. I am assigning this issue to you.

**Comment by arpitghura** [comment]
The issue is now resolved so I am closing it.
