### ISSUE TITLE
[FEATURE] Improve the content of About Us Page

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/typing-test#70]
**Describe the solution you'd like**
The content available on about us page is not looking professional. Make some changes to the content and also fix the alignment of the content.

Currently the content is badly formatted and also not aligned properly. 
![image](https://user-images.githubusercontent.com/41796013/207140636-84f2800a-22fc-415c-b1d7-428207a1447d.png)

**Comment by amitsethii** [comment]
please assign this to me

**Comment by amitsethii** [comment]
> please assign this to me

**Comment by arpitghura** [comment]
ok @amitsethii, I am assigning this issue to you.

**Comment by arpitghura** [comment]
The issue is resolved so I am closing it
