### ISSUE TITLE
[FEATURE]imroving the navbar

### ISSUE THREAD

**Issue by NiharikaSharma18** [arpitghura/typing-test#75]
**Is your feature request related to a problem? Please describe.**
i will improve the nav var and make it more attractive
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by NiharikaSharma18** [comment]
@arpitghura plz assign this issue to me

**Comment by somya-kr** [comment]
Hey @arpitghura , assign this issue to me

**Comment by NiharikaSharma18** [comment]
@arpitghura  please assign me under kwoc

**Comment by arpitghura** [comment]
What Improvements can be made in navBar? Can you please describe?

**Comment by prehans** [comment]
@arpitghura can you please assign this issue to me?

**Comment by NiharikaSharma18** [comment]
i Make it more attractive.
