### ISSUE TITLE
[BUG] Remove unwanted space between GitHub icon and dark mode button

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/typing-test#76]
**Describe the bug**
The GitHub Button and dark mode button has unwanted space in middle on all pages except `index.html`, remove it.

**Expected behavior**
Both the GitHub icon and dark mode button be adjacent.

**Screenshots**
![image](https://user-images.githubusercontent.com/41796013/212557808-a21ee431-1ec8-493e-9c9c-b510879995d3.png)

**Comment by zemetskiym** [comment]
I would like to contribute to this bug if possible. I have opened a pull request with a solution.

**Comment by arpitghura** [comment]
Hey I have reviewed your PR and merged it. Thank you for your contribution @zemetskiym
