### ISSUE TITLE
[Improvement] Update the Dark Mode button content from text to icon

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/typing-test#77]
What to do?
Remove the text of the dark Mode button and add icon to it. 
You can check out the icon that I am saying on Reactjs documentation page, [Click here](https://beta.reactjs.org/) to view.

**Comment by c00kie123** [comment]
hey can give more info? What does it look like currently and what do you want it to look like?

**Comment by arpitghura** [comment]
> hey can give more info? What does it look like currently and what do you want it to look like?

Currently, the button look like 
![image](https://user-images.githubusercontent.com/41796013/212735346-51f5dacf-a6b7-4981-ad57-85b2751cc69e.png)

I want the button should be like below:

1. For light mode
![image](https://user-images.githubusercontent.com/41796013/212735419-c564bed3-5101-40c5-96b8-5255e5f51cf4.png)

2. For Dark mode
![image](https://user-images.githubusercontent.com/41796013/212735431-25b915ed-1e2d-4ac3-96fa-67b4e0b7dc0b.png)

**Comment by c00kie123** [comment]
I dont seem to find the button anywhere on the live website. Where it is?

**Comment by arpitghura** [comment]
Hey @c00kie123 You can view the button of darkMode on all pages other than `index.html`

**Comment by chikkibum** [comment]
@arpitghura hey i have solved this issue. Can you assign it to me. I'd like to make a pull request.

i added <i id="icon1" onlick="change('icon1')" onclick="toggleLightDarkMode()" class="bx bx-moon dark-btn" style="font-size: x-large;"></i>  in practice.html.

![practice](https://user-images.githubusercontent.com/71315985/215353206-29e0105f-e905-4824-9d65-31410de306b1.png)


similarly, I added <i id="icon1" onlick="change('icon1')" onclick="toggleLightDarkMode()" class="bx bx-moon dark-btn" style="font-size: x-large;"></i> to about and profile page also.

Then i added js to change the icon from moon to sun using 
`function change (iconID){
    if(document.getElementById(iconID).className=="bx bx-moon dark-btn"){
      document.getElementById(iconID).className = "bx bx-sun dark-btn";
    }
else{
      document.getElementById(iconID).className = "bx bx-moon dark-btn";
    }
  }
`

![icon](https://user-images.githubusercontent.com/71315985/215353499-9e170482-c1ee-4a89-bb45-7fa67ec41b91.png)

and called it whenever needed.


here is a video attached to show that its working:

https://user-images.githubusercontent.com/71315985/215354809-5e2c73e5-95be-4ba4-8fbb-fb2a110ff76b.mp4

**Comment by arpitghura** [comment]
Hey @chikkibum Welcome to the community. You have done a good job. I will assigned the task to you. You can now create a PR.
