### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/typing-test#8]
Improve Readme.md file to give information about the project. 
Add some badges relevant to the project.

**Comment by iharshka** [comment]
Hello @arpitghura ,
Hope you are doing well!
I am interested in doing this project. Can you assign it to me?

**Comment by sajal-19** [comment]
hye @arpitghura  i am very interested to contribute in this . So kindly assign this issue to me as well.

**Comment by arpitghura** [comment]
Hey, @sajal-19 Welcome to the **community**. 
@iharshka is already working on this issue till then you can look into some other issue or if you find any bug or issues in the website create an issue and solve it if you can.
