### ISSUE TITLE
Update Images in README file

### ISSUE THREAD

**Issue by arpitghura** [arpitghura/typing-test#88]
The Webpage images available in the README file are outdated. Update the file as per the current state of the project.

**Comment by Yash-Var** [comment]
@arpitghura i will complete it ps assign it  to me...

**Comment by arpitghura** [comment]
Hello @Yash-Var Welcome to the community. I am assigning you the issue.

**Comment by Yash-Var** [comment]
@arpitghura i have seen the readme and find that the image are already updated...

**Comment by arpitghura** [comment]
> @arpitghura i have seen the readme and find that the image are already updated...

They are not. The Homepage Image is updated but rest of all are not updated.

**Comment by Yash-Var** [comment]
okay @arpitghura i will completed .....

**Comment by arpitghura** [comment]
Hey @Yash-Var Are you working on the issue?

**Comment by Yash-Var** [comment]
@arpitghura yes sorry for tgr delay i will completed it today..

**Comment by chikkibum** [comment]
hey @arpitghura if the work is still in progress, then I would gladly work on this.

**Comment by GitWiz01** [comment]
@arpitghura are you still working on it ?

**Comment by anushkaaa34** [comment]
@arpitghura please assign it to me. I'll update it

**Comment by arpitghura** [comment]
Hey, @Preeti8021 assigning this issue to you. Go ahead.
Meanwhile @anushkaaa34 you can look at some other issues. 

Thank you

**Comment by Preeti8021** [comment]
Thank you!!
