### ISSUE TITLE
[BUG] Quote is not sufficiently long/does not extend

### ISSUE THREAD

**Issue by zemetskiym** [arpitghura/typing-test#89]
**Describe the bug**
When taking the timed typing test, the sample text to copy can be completed before the timer runs out. When this happens, no extra text is allotted and the highlight disappears, leaving the visitor to wait until the timer runs out. The words per minute (WPM) displayed once the timer runs out is not representative of the end user's skill because the quote was not sufficient.

**To Reproduce**
1. Go to the "Practice" section
2. Click on the easy difficulty and the 5 minute option
3. Finish typing the sample text

**Expected behavior**
The expected behavior would be the sample text extending as the user types or the original sample text being too long for any human to reasonably complete.

**Screenshots**
![image](https://user-images.githubusercontent.com/122832270/215934763-6809a002-1a56-416a-8d15-07ee4bc33c45.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 109.0 (64-bit)

**Expected Solution**
This bug can be solved by generating more sample text or checking for a completed test to create additional text.

**Comment by arpitghura** [comment]
Hey @zemetskiym, Thanks for noticing this bug. This is the problem in every case of difficulty. 
We need to solve this issue so that it would not affect the user experience. 

If you see our code, currently we are generating text from a set of words (incl. nouns, pronouns, verbs, adjectives, prepositions, etc.) and for each difficulty level we are generating only a set of words which we repeated so that the length of the sentence increases but we need a different approach to generate words as per difficulty level, time given and the user's speed. 

Are you able to think of any such approach, do let me know. I am also working on it to find a good solution.

**Comment by aviiciii** [comment]
Hey @arpitghura, I looked at the code for generating quote length
```javascript
// making the quote from the words
const makequote = () => {
    // setting up difficulty level 
    if (easyLvlBtn.checked) {
        selectedDifficultyLevel = "easy";
        quoteLength = 30
    } else if (interLvlBtn.checked) {
        selectedDifficultyLevel = "medium";
        quoteLength = 50
    } else if (hardLvlBtn.checked) {
        selectedDifficultyLevel = "hard";
        quoteLength = 60
    }
    return makeSentence(selectedDifficultyLevel,quoteLength);
};
```

1. Consider the condition when the user selects easy difficulty, then it is likely for the user to type faster thereby typing more words. But if the user goes with a higher difficulty, the words generated is harder and user types slower. So the logic must be inverted in the about snippet. 
2. Also, we have the highest wpm of the user from his history of typing in the user's local storage. We can also use that to generate words per user. Ideally, Words = Highest WPM + 10 Words so the user has a buffer region to break his personal record. 

If you agree that this is a feasible solution, assign me this and I will work on it.

**Comment by arpitghura** [comment]
> Hey @arpitghura, I looked at the code for generating quote length
> 
> ```js
> // making the quote from the words
> const makequote = () => {
>     // setting up difficulty level 
>     if (easyLvlBtn.checked) {
>         selectedDifficultyLevel = "easy";
>         quoteLength = 30
>     } else if (interLvlBtn.checked) {
>         selectedDifficultyLevel = "medium";
>         quoteLength = 50
>     } else if (hardLvlBtn.checked) {
>         selectedDifficultyLevel = "hard";
>         quoteLength = 60
>     }
>     return makeSentence(selectedDifficultyLevel,quoteLength);
> };
> ```
> 
> 1. Consider the condition when the user selects easy difficulty, then it is likely for the user to type faster since the generated quote is easy thereby typing more words. But if the user goes with a higher difficulty, the quote generated is harder and user types slower. So the logic must be inverted in the about snippet of code.
> 2. Also, we have the highest wpm of the user from his history of typing in the user's local storage. We can also use that to generate words per user. Ideally, Words = Highest WPM + 10 Words so the user has a buffer region to break his personal record.
> 
> If you agree that this is a feasible solution, assign me this and I will work on it.

That's a great idea. Go ahead and fix this bug. I am assigning this issue to you.

**Comment by aviiciii** [comment]
Pull request #113 solved this issue.
