### ISSUE TITLE
[ENHANCEMENT] Code Documentation

### ISSUE THREAD

**Issue by aviiciii** [arpitghura/typing-test#91]
**Describe the bug**
No Descriptions on the code blocks or snippets. Only identifier is the class of the html conponents.

**To Reproduce**
1. Open the source in an editor

**Expected behavior**
Need short description on code blocks to quickly grasp the structure of the code

**Screenshots**
![image](https://user-images.githubusercontent.com/88141521/216083981-1e95864c-34c1-4a61-8693-3b3cb7d362ce.png)

**Expected Solution**
This bug can be solved by writing a short description on top of code blocks.

**Comment by aviiciii** [comment]
@arpitghura Can I document the code by providing short descriptions under diversion 2k23?

**Comment by aviiciii** [comment]
@arpitghura Shall I go ahead with the proposed code enhancement?

**Comment by arpitghura** [comment]
Yeah go a head @aviiciii

**Comment by aviiciii** [comment]
@arpitghura I have completed documentation and open a pull request #109 . Kindly look into my work and merge if no changes is required.
