### ISSUE TITLE
[FEATURE] About Section ui

### ISSUE THREAD

**Issue by niladrix719** [arpitghura/typing-test#98]
**Is your feature request related to a problem? Please describe.**
The About section looks very basic 

**Describe the solution you'd like**
To enhance the UI of the About section

![Screenshot from 2023-02-03 18-23-12](https://user-images.githubusercontent.com/91966855/216608463-62db2191-00cf-4ab6-8914-d92660f7cdf0.png)

**Comment by arpitghura** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face: <br/> You should join our <a href='https://discord.gg/7c3VGDutmS'>Discord</a> chat - we help and encourage each other to contribute to open source little and often
