### ISSUE TITLE
Better Navigation menu for more attraction

### ISSUE THREAD

**Issue by Rupayan20** [arpitghura/typing-test#99]
The UI of the website is not so good. we need to implement with modern and attractive designs.
We need to more attractive the About & Profile section.

**Comment by arpitghura** [comment]
<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face: <br/> You should join our <a href='https://discord.gg/7c3VGDutmS'>Discord</a> chat - we help and encourage each other to contribute to open source little and often

**Comment by Tapo41** [comment]
I want to contribute.. Please assign it to me

**Comment by TheXro** [comment]
@arpitghura  i want to work on this issue i have tried adding icons in the nav bar 
it will look like this 
![Screenshot 2023-02-04 at 22-40-00 Typing Test Test and practice your typing skills](https://user-images.githubusercontent.com/84002250/216780316-2bca3c1e-da0a-4620-88e3-cbb28c774b75.png)

**Comment by arpitghura** [comment]
Hey @TheXro Please go ahead. I am assigning this issue to you. All the best.

**Comment by arpitghura** [comment]
> @arpitghura i want to work on this issue i have tried adding icons in the nav bar it will look like this ![Screenshot 2023-02-04 at 22-40-00 Typing Test Test and practice your typing skills](https://user-images.githubusercontent.com/84002250/216780316-2bca3c1e-da0a-4620-88e3-cbb28c774b75.png)

Are you contributing through any project like Diversion2k23 or IWOC?

**Comment by TheXro** [comment]
> > @arpitghura i want to work on this issue i have tried adding icons in the nav bar it will look like this ![Screenshot 2023-02-04 at 22-40-00 Typing Test Test and practice your typing skills](https://user-images.githubusercontent.com/84002250/216780316-2bca3c1e-da0a-4620-88e3-cbb28c774b75.png)
> 
> Are you contributing through any project like Diversion2k23 or IWOC?

yes iwoc

**Comment by TheXro** [comment]
@arpitghura i have sent the pull request please review it
